package com.los.loanoriginatingsystem.document.entity;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Table(name = "document_checklist")
@Data
public class DocumentChecklist {

    @Id
    private String id;

    @Column(name = "loan_product_code")
    private String loanProductCode;

    @Column(name = "document_type")
    private String documentType;

    @Column(name = "auto_generated")
    private Boolean autoGenerated;

    @Column(nullable = false)
    private Boolean active = true;

    private String description;
}