server:
  port: 8085

spring:

  application:
    name: api-gateway

  cloud:

    gateway:

      globalcors:
        add-to-simple-url-handler-mapping: true

        cors-configurations:

          '[/**]':

            allowedOriginPatterns:
              - "http://localhost:*"

            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS

            allowedHeaders:
              - "*"

            allowCredentials: true

      routes:

        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**

        - id: administration-service
          uri: http://localhost:8080
          predicates:
            - Path=/users/**,/admin/users/**,/admin/roles/**,/admin/profiles/**
          filters:
            - JwtValidation

        - id: los-admin-service
          uri: http://localhost:8081
          predicates:
            - Path=/admin/employees/**,/admin/branches/**,/admin/employee-branch-mappings/**,/admin/departments/**,/admin/designations/**,/admin/languages/**,/admin/hierarchy-rules/**,/admin/roles/**
          filters:
            - JwtValidation

        - id: los-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
          filters:
            - JwtValidation

eureka:
  client:
    enabled: false

auth:
  service:
    url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"