package com.los.loanoriginatingsystem.document.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
public class DocumentChecklistRequest {

    @NotBlank private String loanProductCode;
    @NotBlank private String documentType;
    private Boolean autoGenerated;
    private String description;
}
