package com.los.loanoriginatingsystem.document.service;

import com.los.loanoriginatingsystem.common.exception.ResourceNotFoundException;
import com.los.loanoriginatingsystem.document.dto.DocumentChecklistRequest;
import com.los.loanoriginatingsystem.document.entity.DocumentChecklist;
import com.los.loanoriginatingsystem.document.repository.DocumentChecklistRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

/**
 * Admin CRUD + activation for the required-document checklist per loan
 * product. Was previously seed-data-only (no way to add/edit/retire a
 * required document type without editing db/document/document-checklist.sql
 * directly) - now a real admin surface, and the source LoanStageGuardService
 * reads from to block Sanction -> Pre-Disbursal Review until satisfied.
 */
@Service
@RequiredArgsConstructor
public class DocumentChecklistAdminService {

    private final DocumentChecklistRepository repository;

    @Transactional
    public DocumentChecklist create(DocumentChecklistRequest request) {
        DocumentChecklist entity = new DocumentChecklist();
        entity.setId(UUID.randomUUID().toString());
        entity.setActive(true);
        apply(entity, request);
        return repository.save(entity);
    }

    @Transactional
    public DocumentChecklist update(String id, DocumentChecklistRequest request) {
        DocumentChecklist entity = getOrThrow(id);
        apply(entity, request);
        return repository.save(entity);
    }

    @Transactional
    public DocumentChecklist setActive(String id, boolean active) {
        DocumentChecklist entity = getOrThrow(id);
        entity.setActive(active);
        return repository.save(entity);
    }

    public List<DocumentChecklist> getAll() {
        return repository.findAll();
    }

    public List<DocumentChecklist> getByProductCode(String loanProductCode) {
        return repository.findByLoanProductCodeAndActiveTrue(loanProductCode);
    }

    private void apply(DocumentChecklist entity, DocumentChecklistRequest request) {
        entity.setLoanProductCode(request.getLoanProductCode());
        entity.setDocumentType(request.getDocumentType());
        entity.setAutoGenerated(request.getAutoGenerated() != null ? request.getAutoGenerated() : Boolean.FALSE);
        entity.setDescription(request.getDescription());
    }

    private DocumentChecklist getOrThrow(String id) {
        return repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Document checklist entry not found: " + id));
    }
}
