spring.application.name=loan-originating-system

aa.base-url=https://AA_ENDPOINT
aa.bank-statement-url=https://AA_BANK_STATEMENT_ENDPOINT
aa.token=YOUR_TOKEN

# Aadhaar OCR (Multipart)
http.clients.aadhaar-ocr.base-url=https://api.aadhaar/ocr
http.clients.aadhaar-ocr.method=POST
http.clients.aadhaar-ocr.content-type=multipart/form-data
http.clients.aadhaar-ocr.timeout=5000

# Aadhaar Verify (JSON)
http.clients.aadhaar-verify.base-url=https://api.aadhaar/verify
http.clients.aadhaar-verify.method=POST
http.clients.aadhaar-verify.content-type=application/json
http.clients.aadhaar-verify.timeout=5000

# PAN
http.clients.pan.base-url=https://pan.api
http.clients.pan.method=POST
http.clients.pan.content-type=application/json
http.clients.pan.timeout=5000


# =============================
# KAFKA CONFIG
# =============================
spring.kafka.bootstrap-servers=localhost:9092

# Producer settings
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Optional but recommended
spring.kafka.producer.properties.spring.json.add.type.headers=false  

# batching + performance
spring.kafka.producer.linger-ms=5
spring.kafka.producer.batch-size=16384

# compression
spring.kafka.producer.compression-type=snappy

# idempotency (VERY IMPORTANT ?)
spring.kafka.producer.enable-idempotence=true